services:
  database:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-100Senha}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASS:-100Senha}
      MYSQL_DATABASE: ${DB_NAME:-ecommerce}
    restart: unless-stopped
    networks:
      - docker-service

  api-server:
    build: .
    container_name: api-backend
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - docker-service
    depends_on:
      - database

networks:
  docker-service:
    driver: bridge
